# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polymer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
